Repository ValeryiaPilchuk/Never_Late, pull requests merged in 2021-11, with the labels that each got.

#27 version_1 pdf scan using tabula and pdfplumber librar
  src/components/pdf_scan.py
Labels: python

#39 Profile pic
  client/package-lock.json
  client/package.json
  client/src/components/Photo.js
  client/src/components/Profile.js
  client/src/components/UploadAndDisplayImage.js
Labels: profile

#43 unit testing in Photo.js
  client/package-lock.json
  client/package.json
  client/src/__tests__/Photo.test.js
  client/src/components/Photo.js
Labels: unit_testing, profile
